/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.DAOCliente;
import modelo.DAOproducto;
import modelo.DAOVenta;
import modelo.Cliente;
import modelo.producto;
import modelo.venta;
import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author juriel
 */
public class JFrameVenta_Detalle extends javax.swing.JFrame {
    
    private DefaultTableModel modelotablaventa;
    private Object[] objetoventaTable = new Object[6];
    private Double total=0.0;
    private int item= 0;
    private Date fech;
    private int cantidad=0;
    private int ventaid=0;
    private int productoid;
    
    public JFrameVenta_Detalle() {
        initComponents();
        jTextcantidad.setText("0");
        jDialogcliente.setLocationRelativeTo(null);
        jDialogproducto.setLocationRelativeTo(null);
        jTextidcliente.setEnabled(false);
        jTextIDproducto.setEnabled(false);
        fech= java.sql.Date.valueOf(LocalDate.now());
        jLabelfecha.setText(fech.toString());
        
        modelotablaventa=(DefaultTableModel) jTproductoventa.getModel();
    }
    
    public void limpiarcampo(){
        jTextIDproducto.setText("0");
        jTextdescripcion.setText("");
        jTextprecioproducto.setText("0.0");
        jTextExistencia.setText("0");
        jTextcantidad.setText("0");
    }
    
    private void buscarcliente(String datos)throws SQLException{
        List<Cliente> clientes=new DAOCliente().buscarCliente(datos);
        
        DefaultTableModel modelo=new DefaultTableModel();
        
        String[] columnas={"cliente_id", "Nombre", "Apellido","telefono",
        "direccion"};
        
       modelo.setColumnIdentifiers(columnas);
       for (Cliente cli : clientes){
           String[] renglon = {Integer.toString(cli.getcliente_id()),
               cli.getNombre(),cli.getApellido(), cli.getTelefono(), cli.getDireccion()};
           modelo.addRow(renglon);
       }
       jTablebuscarcliente.setModel(modelo);
    }
    
    
    
    private void buscarproducto(String dato)throws SQLException{
        List<producto> productos = new DAOproducto().buscarproducto(dato);
        DefaultTableModel modelo=new DefaultTableModel();
        String[] columnas ={"producto_id", "descripcion", 
        "precio_produc", "Existencia"};
        
        modelo.setColumnIdentifiers(columnas);
        for(producto pro:productos){
            String[] renglon ={Integer.toString(pro.getProducto_id()),
            pro.getDescripcion(), Double.toString(pro.getPrecio_produc()),
            Integer.toString(pro.getExistencia())};
            modelo.addRow(renglon);
        }
        jTablebuscarProduct.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField13 = new javax.swing.JTextField();
        jDialogproducto = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jTextproduct = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jBAñadir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablebuscarProduct = new javax.swing.JTable();
        jDialogcliente = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextclientebuscar = new javax.swing.JTextField();
        jBcliente = new javax.swing.JButton();
        jBagregarcliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablebuscarcliente = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextIDproducto = new javax.swing.JTextField();
        jTextdescripcion = new javax.swing.JTextField();
        jBbuscarproducto = new javax.swing.JButton();
        jTextprecioproducto = new javax.swing.JTextField();
        jTextExistencia = new javax.swing.JTextField();
        jTextcantidad = new javax.swing.JTextField();
        jBAgregar = new javax.swing.JButton();
        jBQuitar = new javax.swing.JButton();
        jLabelfecha = new javax.swing.JLabel();
        jTextpago = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextidcliente = new javax.swing.JTextField();
        jTextCliente = new javax.swing.JTextField();
        jBCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTproductoventa = new javax.swing.JTable();
        jlabeltotal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jDialogproducto.setSize(new java.awt.Dimension(600, 600));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Buscar Producto");

        jBBuscar.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBAñadir.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jBAñadir.setText("Añadir");
        jBAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAñadirActionPerformed(evt);
            }
        });

        jTablebuscarProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablebuscarProduct);

        javax.swing.GroupLayout jDialogproductoLayout = new javax.swing.GroupLayout(jDialogproducto.getContentPane());
        jDialogproducto.getContentPane().setLayout(jDialogproductoLayout);
        jDialogproductoLayout.setHorizontalGroup(
            jDialogproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogproductoLayout.createSequentialGroup()
                .addGroup(jDialogproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogproductoLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel4))
                    .addGroup(jDialogproductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jBBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jBAñadir))
                    .addGroup(jDialogproductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogproductoLayout.setVerticalGroup(
            jDialogproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogproductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar)
                    .addComponent(jBAñadir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Buscar Clientes");

        jBcliente.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jBcliente.setText("Buscar");
        jBcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclienteActionPerformed(evt);
            }
        });

        jBagregarcliente.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jBagregarcliente.setText("Añadir");
        jBagregarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarclienteActionPerformed(evt);
            }
        });

        jTablebuscarcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTablebuscarcliente);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextclientebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jBcliente)
                        .addGap(18, 18, 18)
                        .addComponent(jBagregarcliente))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextclientebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcliente)
                    .addComponent(jBagregarcliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogclienteLayout = new javax.swing.GroupLayout(jDialogcliente.getContentPane());
        jDialogcliente.getContentPane().setLayout(jDialogclienteLayout);
        jDialogclienteLayout.setHorizontalGroup(
            jDialogclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogclienteLayout.setVerticalGroup(
            jDialogclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(63, 218, 132));
        jPanel3.setForeground(new java.awt.Color(0, 153, 102));

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Dollar");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Store");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jLabel6.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Venta ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jTextIDproducto.setText("ID");

        jTextdescripcion.setText("Producto");

        jBbuscarproducto.setBackground(new java.awt.Color(255, 255, 255));
        jBbuscarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/buscar.png"))); // NOI18N
        jBbuscarproducto.setText("Buscar");
        jBbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarproductoActionPerformed(evt);
            }
        });

        jTextprecioproducto.setText("Precio producto");

        jTextExistencia.setText("Existencia");

        jTextcantidad.setText("Cantidad");

        jBAgregar.setBackground(new java.awt.Color(0, 153, 51));
        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/boton-agregar.png"))); // NOI18N
        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBQuitar.setBackground(new java.awt.Color(255, 51, 51));
        jBQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/eliminar (1).png"))); // NOI18N

        jLabelfecha.setText("Fecha");

        jTextpago.setText("Pago");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextIDproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextprecioproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jBbuscarproducto)
                        .addGap(46, 46, 46)
                        .addComponent(jLabelfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextpago, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextExistencia, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(55, 55, 55)
                        .addComponent(jTextcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jBAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(jBQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIDproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscarproducto)
                    .addComponent(jTextprecioproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelfecha))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBQuitar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBAgregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTextidcliente.setText("ID");

        jTextCliente.setText("Cliente");

        jBCliente.setBackground(new java.awt.Color(255, 255, 255));
        jBCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/buscar.png"))); // NOI18N
        jBCliente.setText("Buscar");
        jBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBCliente)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCliente))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTproductoventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTproductoventa);

        jlabeltotal.setText("Total");

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/boton-agregar.png"))); // NOI18N
        jButton2.setText("Agregar");

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/eliminar (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlabeltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlabeltotal)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarproductoActionPerformed
        // TODO add your handling code here:
        jDialogproducto.setVisible(true);
    }//GEN-LAST:event_jBbuscarproductoActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        if(jTextproduct.getText().contentEquals("")){
               JOptionPane.showMessageDialog(rootPane,
                    "Ingrese texto a buscar");
        }else{
            try{
             String datopro=jTextproduct.getText();
                buscarproducto(datopro);
                jTextproduct.setText("");
            }catch(SQLException ex){
                 Logger.getLogger(JFrameVenta_Detalle.class.getName()).
                        log(Level.SEVERE,null,ex); 
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAñadirActionPerformed
        // TODO add your handling code here:
        int fila =this.jTablebuscarProduct.getSelectedRow();
                if(fila==-1){
                     JOptionPane.showMessageDialog(rootPane, 
                    "Seleccione un registro de la tabla"); 
                }else{
                    try{
                      int id=Integer.parseInt((String)this.jTablebuscarProduct.
                              getValueAt(fila, 0).toString());
                      String des=(String)this.jTablebuscarProduct.getValueAt(fila, 1);
                      float precio=Float.parseFloat((String)this.jTablebuscarProduct.
                              getValueAt(fila, 2).toString());
                      int exi=Integer.parseInt((String)this.jTablebuscarProduct.
                              getValueAt(fila, 3).toString());
                      
                      jTextIDproducto.setText(""+id);
                      jTextdescripcion.setText(des);
                      jTextprecioproducto.setText(""+precio);
                      jTextExistencia.setText(""+exi);
                    }catch(NumberFormatException e){
                         JOptionPane.showMessageDialog(rootPane,
                      "Ocurrio un Error!"+e.getMessage());
                    }
                }
    }//GEN-LAST:event_jBAñadirActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        if(jTextcantidad.getText().contentEquals("0")){
            JOptionPane.showMessageDialog(rootPane,
                    "Escriba la cantidad de producto");
        }else{
            if(Integer.parseInt(jTextcantidad.getText().trim())>
                    Integer.parseInt(jTextExistencia.getText().trim())){
                JOptionPane.showMessageDialog(rootPane,
                        "La cantidad indicada supera la existencia actual"+
                                "del producto");
            }else{
                item+=1;
                
                objetoventaTable[0]=item;
                
                 objetoventaTable[1]= jTextIDproducto.getText().trim();
                objetoventaTable[2]= jTextdescripcion.getText().trim();
                 objetoventaTable[3]=jTextcantidad.getText().trim();
                 objetoventaTable[4]=jTextprecioproducto.getText().trim();
                
                Double subtotal= Double.parseDouble(jTextcantidad.getText().trim())
                        *Double.parseDouble(jTextprecioproducto.getText().trim());
                
                objetoventaTable[5]=subtotal;
                total+=subtotal;
                
                jlabeltotal.setText(total.toString());
                
                modelotablaventa.addRow(objetoventaTable);
                
                limpiarcampo();
                
                
            }
        }
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClienteActionPerformed
        // TODO add your handling code here:
        jDialogcliente.setVisible(true);
    }//GEN-LAST:event_jBClienteActionPerformed

    private void jBclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclienteActionPerformed
        // TODO add your handling code here:
        if(jTextclientebuscar.getText().contentEquals("")){
            JOptionPane.showMessageDialog(rootPane,
                    "Ingrese texto a buscar");
        }else{
            try{
                String datocli=jTextclientebuscar.getText();
                buscarcliente(datocli);
                jTextclientebuscar.setText("");
            }catch(SQLException ex){
                 Logger.getLogger(JFrameVenta_Detalle.class.getName()).
                        log(Level.SEVERE,null,ex); 
            }
        }
    }//GEN-LAST:event_jBclienteActionPerformed

    private void jBagregarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarclienteActionPerformed
        // TODO add your handling code here:
        int fila =this.jTablebuscarcliente.getSelectedRow();
        if(fila==-1){
              JOptionPane.showMessageDialog(rootPane, 
                    "Seleccione un registro de la tabla");
        }else{
            try{
                int id=Integer.parseInt((String)this.jTablebuscarcliente.
                        getValueAt(fila, 0).toString());
                String nom=(String)this.jTablebuscarcliente.getValueAt(fila, 1);
                String ape=(String)this.jTablebuscarcliente.getValueAt(fila, 2);
                
                jTextidcliente.setText(""+id);
                jTextCliente.setText(nom+""+ape);
            }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(rootPane, 
                        "Ocurrio un Error!"+e.getMessage());
            }
        }
    }//GEN-LAST:event_jBagregarclienteActionPerformed

    public void guardarventa()throws SQLException{
        if (jTextidcliente.getText().contentEquals("")||
                jLabelfecha.getText().contentEquals("")|| 
                jTproductoventa.getRowCount() == 0){
            JOptionPane.showMessageDialog(rootPane, 
              "Se requieren datos del cliente y producto, "
            + "fecha");
            
        } else {
            try{
                //Captura los datos de los jtext en JFrame Venta
                int cliente_id = Integer.parseInt(jTextidcliente.getText());
            
                venta vent = new venta(cliente_id, fech);
                //Objeto de DAOVenta
                DAOVenta daoventa = new DAOVenta();
                //Llamada al método insertar una venta, si el resultado es exitoso
                //regresa un 0
                if (daoventa.insertarventa(vent) == 0){
                    JOptionPane.showMessageDialog(rootPane, 
                            "Registro agregado en venta");
                    //------Obtiene el último número de factura generado------//
                       //Se le asigna a una venta global numfac
                    ventaid = daoventa.obtenerUltimoventaid();

                } else {
                    JOptionPane.showMessageDialog(rootPane, 
                         "Ha ocurrido un error, no se insertó en venta");
                }
            } catch (HeadlessException | SQLException e){
                 JOptionPane.showMessageDialog(rootPane, 
                         "No se agregaron los registros " + e);
            }
            JOptionPane.showMessageDialog(rootPane,
                    "No se agregaron los registros" + ventaid);
            //Si la venta se guarda exitosa, se guardan los detalles******
         //   guardarDetalleVenta();//Llamado al método que guarda los detalles
//Actualiza existencia de productos******************
        //    actualizarExistencia();
        } 
    }
        
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVenta_Detalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBAñadir;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCliente;
    private javax.swing.JButton jBQuitar;
    private javax.swing.JButton jBagregarcliente;
    private javax.swing.JButton jBbuscarproducto;
    private javax.swing.JButton jBcliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialogcliente;
    private javax.swing.JDialog jDialogproducto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelfecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablebuscarProduct;
    private javax.swing.JTable jTablebuscarcliente;
    private javax.swing.JTextField jTextCliente;
    private javax.swing.JTextField jTextExistencia;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextIDproducto;
    private javax.swing.JTextField jTextcantidad;
    private javax.swing.JTextField jTextclientebuscar;
    private javax.swing.JTextField jTextdescripcion;
    private javax.swing.JTextField jTextidcliente;
    private javax.swing.JTextField jTextpago;
    private javax.swing.JTextField jTextprecioproducto;
    private javax.swing.JTextField jTextproduct;
    private javax.swing.JTable jTproductoventa;
    private javax.swing.JLabel jlabeltotal;
    // End of variables declaration//GEN-END:variables
}
